### ISSUE TITLE
Sigma allah

### ISSUE THREAD

**Issue by ghost** [XatzClient/Sigma-Deleter#10]
Omikron allah

**Comment by Invy55** [comment]
> Omikron

Omikron

**Comment by terrified9** [comment]
> > Omikron
> 
> Omikron

Omikron

**Comment by Invy55** [comment]
> Omikron

Omikron

**Comment by Invy55** [comment]
> > > Omikron
> > 
> > 
> > Omikron
> 
> Omikron

Omikron

**Comment by Napoleon-x** [comment]
> 
> 
> > > > Omikron
> > > 
> > > 
> > > Omikron
> > 
> > 
> > Omikron
> 
> Omikron

Omikron

**Comment by Frozenturbo** [comment]
no, islamphobic, overused sigma joke about owner of sigma is allah

**Comment by ENDER1355** [comment]
> Omikron allah

verpissen

**Comment by pwn3r1** [comment]
> > > > > Omikron
> > > > 
> > > > 
> > > > Omikron
> > > 
> > > 
> > > Omikron
> > 
> > 
> > Omikron
> 
> Omikron

Omikron

**Comment by UseUser123321** [comment]
Omikron
