### ISSUE TITLE
nice rat bro

### ISSUE THREAD

**Issue by ghost** [XatzClient/Sigma-Deleter#16]
very good rat. no one will know. when you realize that the jars don't match the github LMAO

**Comment by ghost** [comment]
Plus, your "video" showing it not be virus is completely false.
When you realize it downloads to %user%\Downloads not C:

**Comment by Napoleon-x** [comment]
> very good rat. no one will know. when you realize that the jars don't match the github LMAO

Ngl the retardation is much when you don't check that the hashes were for an older version....

Literally insane IQ, when you can't even understand a simple language like java...


Go back to watching dream SMP genius
