### ISSUE TITLE
its not even a miner

### ISSUE THREAD

**Issue by 30440r** [XatzClient/Sigma-Deleter#2]
it is a miner i dont know what i was thinking

**Comment by Thereallo1026** [comment]
Imagine editing people's comment

**Comment by Napoleon-x** [comment]
> agreed, they just dumb 🤡
> 
> New "PrOoF" isn't a thing anymore
> https://www.reddit.com/r/SigmaClient/comments/lkwni8/the_folder_sigma_in_the_edge_folder_isnt_created/



> _No description provided._

You are both NN's who are clowns Go mine your fucking IQ and then come back and say not miner

**Comment by Napoleon-x** [comment]
Looking at your Githubs, it is clear you guys make nothing of use or importance

**Comment by Napoleon-x** [comment]
Sigma users be like...

**Comment by Napoleon-x** [comment]
Next time you make an issue, I require Un-Obfuscated code of sigma as proof it is not miner, And ik you no names will never get your hands on that, Happy Mining!

**Comment by HeyaGlitz** [comment]
doesn't matter if it is or isn't a miner, the kids in r/sigmaclient are quite often too dumb to delete Sigma from their machine and when they actually realize it's a miner (hmm why CPU 60% when Sigma open) they'll want to get rid of it.
Simple, right?

**Comment by 30440r** [comment]
> its not even a miner

im an idiot

**Comment by Thereallo1026** [comment]
what, it is never a miner bruh

**Comment by MLGgamingpro** [comment]
> what, it is never a miner bruh

@apple171017 
the point of this is just to delete sigma, nothing else. you could very easily make it delete anything else
