### ISSUE TITLE
Fake Deleter

### ISSUE THREAD

**Issue by MichalikX** [XatzClient/Sigma-Deleter#3]
Well. Problem with all of this is that its a hoax, Sigma is not a miner. This Jar file contains REAL Miner, It will always say that it doesnt exist... Or somekind of error that "its UNREMOVABLE" bUT IN reality it doesnt remove anything, or it does. But puts real miner into your PC. And No Excuses About Its OPEN SOURCE SO THAT IT CANT BE MINER, The problem is you can just fake it. you can just put different source into Open Source.... 
For Example: Real code is:
Install Monero/Sigma-Deleter
Path: c:/users/SIGMAVIRUS
But in the "Open Source" Is:
Delete Edge.files:Sigma.Cryptomining
Remove c:/users/user/Appdata/Roaming/versions/Sigma5
See. you can just easily put different code into source code.
Dont be fooled. Thanks.

-If this gets deleted, This "deleter" is quarantee Fake and make malicious things.

**Comment by Napoleon-x** [comment]
You are the most retarded person I have met, please tell me this is a joke 😂

**Comment by codergautam** [comment]
I've decompiled the JAR file, wdym bruh @MichalikX

**Comment by HeyaGlitz** [comment]
LOL WHAT THE FU*K

**Comment by HeyaGlitz** [comment]
Weird, you trust a closed source, heavily obfuscated client, but dont trust an open source, non-obfuscated program.
That sure makes sense mate!

**Comment by Frozenturbo** [comment]
i mean most people who make their things open source dont actually put malware if they did on an open source jar file then they are the top 10 dumbest  people on the planet

**Comment by HeyaGlitz** [comment]
> 
> 
> i mean most people who make their things open source dont actually put malware if they did on an open source jar file then they are the top 10 dumbest people on the planet

exactly, you can also build the program YOURSELF, which guarantees YOU didn't include any malicious code, if there was any in the first place. goddamn some people are stupid
