### ISSUE TITLE
Make GUI Automatically Close

### ISSUE THREAD

**Issue by MLGgamingpro** [XatzClient/Sigma-Deleter#5]
After clicking the "Delete Sigma now for free" button make it autoclose because why not
(maybe add a console or something that says `Successfully Removed Sigma.jar` etc)

**Comment by Napoleon-x** [comment]
I mean, we got an alert that says "Sigma is gone, your cpu will thank you" is that not good enough?

**Comment by codergautam** [comment]
Fixed in #6
