### ISSUE TITLE
Relicense to MIT

### ISSUE THREAD

**Issue by DexterHaxxor** [XatzClient/Sigma-Deleter#7]
If you want to rid the world of the abomination called Sigma, you should allow more clients to bundle this, so making it MIT would help.

**Comment by Napoleon-x** [comment]
> If you want to rid the world of the abomination called Sigma, you should allow more clients to bundle this, so making it MIT would help.

Basically, as long as you make it say "Credits to Xatz Developments for Sigma Deleter" we won't mind lol

**Comment by HeyaGlitz** [comment]
Napoleon lol you gotta say that explicitly in the license but ok

**Comment by HeyaGlitz** [comment]
MIT License applied
