### ISSUE TITLE
I found a big issue

### ISSUE THREAD

**Issue by G8LOL** [XatzClient/Sigma-Deleter#9]
One of the biggest issues that I found is that you are a sigma hater. ban all sigma hatars

**Comment by Napoleon-x** [comment]
I am sorre but I am sadge because Omikron Allah halal blocked me on twitor I am sadgers so I amkea de deletor, I am very much sigma hator yes yes

**Comment by Invy55** [comment]
> One of the biggest issues that I found is that you are a sigma hater. ban all sigma hatars

Omikron
